### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by peijin94** [igemsoftware2016/USTC-Software-2016#7]
Edited by Hypercube: This issue was just a joke. Please don't take it seriously.

**Comment by eazyjobb** [comment]
不看wiki，不看install。你说没doc就没doc？你看看你的英语水平，好好说人话行不？

**Comment by Smart-Hypercube** [comment]
OMG the whole backend framework is totally a mess it's going to DaoBi quickly

**Comment by Pjer-zhang** [comment]
2333333333333

**Comment by zzrcxb** [comment]
This shi*ty project doesn't deserve 14 stars!
Stupid flask framework, useless smart map, chrome only support! It's gotta be f**king kidding me!
